// data/mockProducts.ts
import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Wireless Headphones',
    sku: 'ELEC-HP-001',
    category: 'Electronics',
    price: 1990,
    stock: 45,
    status: 'Active',
    description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life.',
    weight: '250g',
    dimensions: '18 × 16 × 8 cm',
    warranty: '1 Year',
    createdAt: '01/01/2025',
    updatedAt: '10/05/2025',
  },
  {
    id: 'prod-2',
    name: 'Smart Watch Series 8',
    sku: 'ELEC-SW-002',
    category: 'Electronics',
    price: 8990,
    stock: 32,
    status: 'Active',
    description: 'Advanced smartwatch with health monitoring, GPS tracking, and 18-hour battery.',
    weight: '45g',
    dimensions: '4.5 × 3.8 × 1 cm',
    warranty: '1 Year',
    createdAt: '01/01/2025',
    updatedAt: '09/05/2025',
  },
  {
    id: 'prod-3',
    name: 'Bluetooth Speaker',
    sku: 'ELEC-BS-003',
    category: 'Electronics',
    price: 1290,
    stock: 78,
    status: 'Active',
    description: 'Portable Bluetooth speaker with 360° sound and IPX7 waterproof rating.',
    weight: '300g',
    dimensions: '8 × 8 × 7 cm',
    warranty: '6 Months',
    createdAt: '05/01/2025',
    updatedAt: '08/05/2025',
  },
  {
    id: 'prod-4',
    name: 'Gaming Mouse',
    sku: 'ACC-GM-004',
    category: 'Accessories',
    price: 890,
    stock: 8,
    status: 'Active',
    description: 'High-precision gaming mouse with 16,000 DPI sensor and RGB lighting.',
    weight: '95g',
    dimensions: '12.6 × 6.8 × 4 cm',
    warranty: '1 Year',
    createdAt: '10/01/2025',
    updatedAt: '07/05/2025',
  },
  {
    id: 'prod-5',
    name: 'Mechanical Keyboard',
    sku: 'ACC-MK-005',
    category: 'Accessories',
    price: 2990,
    stock: 55,
    status: 'Inactive',
    description: 'Compact TKL mechanical keyboard with Cherry MX switches and RGB backlight.',
    weight: '800g',
    dimensions: '36 × 14 × 4 cm',
    warranty: '2 Years',
    createdAt: '10/01/2025',
    updatedAt: '01/04/2025',
  },
];
