"use client";

// src/components/stock-management/ReserveStockModal.tsx

import { useEffect, useMemo, useState } from "react";

import { stockService } from "@/services/stock.service";
import type { StockProduct } from "@/types/stock.type";

interface ReserveStockModalProps {
  product: StockProduct | null;
  onClose: () => void;
  onSuccess: (productId: string, newStock: number) => void;
}

const uuidRegex =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export default function ReserveStockModal({
  product,
  onClose,
  onSuccess,
}: ReserveStockModalProps) {
  if (!product) return null;

  return (
    <ReserveStockModalContent
      key={product.id}
      product={product}
      onClose={onClose}
      onSuccess={onSuccess}
    />
  );
}

interface ReserveStockModalContentProps {
  product: StockProduct;
  onClose: () => void;
  onSuccess: (productId: string, newStock: number) => void;
}

function ReserveStockModalContent({
  product,
  onClose,
  onSuccess,
}: ReserveStockModalContentProps) {
  const [orderId, setOrderId] = useState("");
  const [quantity, setQuantity] = useState(1);
  const [expiryMinutes, setExpiryMinutes] = useState(15);
  const [customExpiresAt, setCustomExpiresAt] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    window.addEventListener("keydown", handleEscape);

    return () => {
      window.removeEventListener("keydown", handleEscape);
    };
  }, [onClose]);

  const remainingStock = useMemo(() => {
    return product.stock - quantity;
  }, [product.stock, quantity]);

  const isValidOrderId = uuidRegex.test(orderId);

  async function handleSubmit() {
    if (!isValidOrderId) return;
    if (quantity <= 0) return;
    if (quantity > product.stock) return;

    let expiresAt: string;

    if (expiryMinutes > 0) {
      expiresAt = new Date(Date.now() + expiryMinutes * 60000).toISOString();
    } else {
      if (!customExpiresAt) return;
      expiresAt = new Date(customExpiresAt).toISOString();
    }

    try {
      setSaving(true);

      await stockService.reserveStock(product.id, {
        orderId,
        quantity,
        expiresAt,
      });

      onSuccess(product.id, product.stock - quantity);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="stock-modal-overlay open" onMouseDown={onClose}>
      <div
        className="stock-modal"
        onMouseDown={(event) => event.stopPropagation()}
      >
        <div className="stock-modal-header">
          <div>
            <h3>Reserve stock</h3>
            <p>Temporarily hold units for an order</p>
          </div>

          <button type="button" className="stock-modal-close" onClick={onClose}>
            ×
          </button>
        </div>

        <div className="stock-modal-body">
          <div className="stock-info-box">
            Reserved stock is held for a specific order and released when the
            reservation expires.
          </div>

          <div className="stock-product-strip">
            <div className="stock-product-strip-icon">📦</div>

            <div>
              <div className="stock-product-strip-name">{product.name}</div>
              <div className="stock-product-strip-meta">SKU: {product.sku}</div>
            </div>

            <div className="stock-product-strip-stock">
              <strong>{product.stock} units</strong>
              <span>Available</span>
            </div>
          </div>

          <div className="stock-form-group">
            <label>Order ID</label>

            <input
              type="text"
              placeholder="550e8400-e29b-41d4-a716-446655440000"
              value={orderId}
              onChange={(event) => setOrderId(event.target.value)}
            />

            <small className={orderId && !isValidOrderId ? "danger" : ""}>
              {orderId && !isValidOrderId
                ? "Invalid UUID format"
                : "UUID format — generated by Order Service"}
            </small>
          </div>

          <div className="stock-form-group">
            <label>Quantity to reserve</label>

            <div className="stock-qty-wrap">
              <button
                type="button"
                onClick={() => setQuantity((prev) => Math.max(1, prev - 1))}
              >
                −
              </button>

              <input
                type="number"
                min={1}
                value={quantity}
                onChange={(event) => {
                  const value = Number(event.target.value);
                  setQuantity(Number.isNaN(value) ? 1 : Math.max(1, value));
                }}
              />

              <button
                type="button"
                onClick={() => setQuantity((prev) => prev + 1)}
              >
                +
              </button>
            </div>
          </div>

          <div className="stock-form-group">
            <label>Expires at</label>

            <div className="stock-expire-options">
              <button
                type="button"
                className={expiryMinutes === 15 ? "active" : ""}
                onClick={() => setExpiryMinutes(15)}
              >
                15 min
              </button>

              <button
                type="button"
                className={expiryMinutes === 30 ? "active" : ""}
                onClick={() => setExpiryMinutes(30)}
              >
                30 min
              </button>

              <button
                type="button"
                className={expiryMinutes === 60 ? "active" : ""}
                onClick={() => setExpiryMinutes(60)}
              >
                1 hour
              </button>

              <button
                type="button"
                className={expiryMinutes === 1440 ? "active" : ""}
                onClick={() => setExpiryMinutes(1440)}
              >
                24 hours
              </button>

              <button
                type="button"
                className={expiryMinutes === 0 ? "active" : ""}
                onClick={() => setExpiryMinutes(0)}
              >
                Custom
              </button>
            </div>

            {expiryMinutes === 0 && (
              <input
                type="datetime-local"
                value={customExpiresAt}
                onChange={(event) => setCustomExpiresAt(event.target.value)}
              />
            )}
          </div>

          {remainingStock < 0 && (
            <div className="stock-warn-box">
              Requested qty exceeds available stock.
            </div>
          )}

          {remainingStock >= 0 && remainingStock < 10 && (
            <div className="stock-warn-box">
              After this reservation only {remainingStock} units will remain.
            </div>
          )}

          <div className="stock-preview-chip">
            <span>Remaining available after reservation</span>
            <strong>{Math.max(0, remainingStock)} units</strong>
          </div>
        </div>

        <div className="stock-modal-footer">
          <button
            type="button"
            className="stock-btn-secondary"
            onClick={onClose}
            disabled={saving}
          >
            Cancel
          </button>

          <button
            type="button"
            className="stock-btn-primary purple"
            disabled={
              saving ||
              !isValidOrderId ||
              quantity <= 0 ||
              quantity > product.stock
            }
            onClick={handleSubmit}
          >
            {saving ? "Reserving..." : "Reserve stock"}
          </button>
        </div>
      </div>
    </div>
  );
}